# Generated by Django 4.0.4 on 2024-07-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_of_study', models.TextField()),
                ('study_goals', models.TextField()),
                ('difficulty_level', models.TextField()),
                ('multiple_choice_questions', models.TextField()),
                ('short_answer_questions', models.TextField()),
                ('essay_questions', models.TextField()),
                ('question_id', models.FloatField()),
            ],
        ),
    ]
