# Generated by Django 4.0.4 on 2024-08-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_questions_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='credit',
            field=models.IntegerField(default=3, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='question_id',
            field=models.IntegerField(),
        ),
    ]
